#include "mosaic.h"
#ifdef NDEBUG
#undef NDEBUG
#endif
#include <assert.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unicode/unorm2.h>
#include <unicode/ustring.h>

static uint64_t rng=0x9e3779b97f4a7c15ULL;
static uint32_t rnd(void){rng^=rng<<7;rng^=rng>>9;rng^=rng<<8;return (uint32_t)rng;}
static size_t put_utf8(uint8_t*out,uint32_t cp){if(cp<=0x7f){out[0]=(uint8_t)cp;return 1;}if(cp<=0x7ff){out[0]=(uint8_t)(0xc0|(cp>>6));out[1]=(uint8_t)(0x80|(cp&63));return 2;}if(cp<=0xffff){out[0]=(uint8_t)(0xe0|(cp>>12));out[1]=(uint8_t)(0x80|((cp>>6)&63));out[2]=(uint8_t)(0x80|(cp&63));return 3;}out[0]=(uint8_t)(0xf0|(cp>>18));out[1]=(uint8_t)(0x80|((cp>>12)&63));out[2]=(uint8_t)(0x80|((cp>>6)&63));out[3]=(uint8_t)(0x80|(cp&63));return 4;}
static int icu_norm(const UNormalizer2*n,const uint8_t*in,size_t len,uint8_t**out,size_t*out_len){UErrorCode e=U_ZERO_ERROR;int32_t ulen=0;u_strFromUTF8(NULL,0,&ulen,(const char*)in,(int32_t)len,&e);if(e!=U_BUFFER_OVERFLOW_ERROR&&U_FAILURE(e))return 0;e=U_ZERO_ERROR;UChar*u=(UChar*)malloc((size_t)(ulen+1)*sizeof* u);if(!u)return 0;u_strFromUTF8(u,ulen+1,&ulen,(const char*)in,(int32_t)len,&e);if(U_FAILURE(e)){free(u);return 0;}e=U_ZERO_ERROR;int32_t need=unorm2_normalize(n,u,ulen,NULL,0,&e);if(e!=U_BUFFER_OVERFLOW_ERROR&&U_FAILURE(e)){free(u);return 0;}e=U_ZERO_ERROR;UChar*v=(UChar*)malloc((size_t)(need+1)*sizeof*v);if(!v){free(u);return 0;}int32_t got=unorm2_normalize(n,u,ulen,v,need+1,&e);free(u);if(U_FAILURE(e)){free(v);return 0;}e=U_ZERO_ERROR;int32_t bneed=0;u_strToUTF8(NULL,0,&bneed,v,got,&e);if(e!=U_BUFFER_OVERFLOW_ERROR&&U_FAILURE(e)){free(v);return 0;}e=U_ZERO_ERROR;uint8_t*b=(uint8_t*)malloc((size_t)bneed+1);if(!b){free(v);return 0;}u_strToUTF8((char*)b,bneed+1,&bneed,v,got,&e);free(v);if(U_FAILURE(e)){free(b);return 0;}*out=b;*out_len=(size_t)bneed;return 1;}
static void check_mapping(const mosaic_normalized_view*v,size_t input_len){uint64_t end=0;for(size_t i=0;i<v->unit_count;i++){const mosaic_normalized_unit*u=&v->units[i];assert(u->output_start==end);assert(u->output_length>0);assert((uint64_t)u->source_span_index+u->source_span_count<=v->source_span_count);assert(u->source_span_count>0);for(uint32_t j=0;j<u->source_span_count;j++){mosaic_range r=v->source_spans[u->source_span_index+j];assert(r.length>0);assert(r.start<=input_len);assert(r.length<=input_len-r.start);}end+=u->output_length;}assert(end==v->byte_length);}
int main(int argc,char**argv){assert(argc==4);mosaic_normalization*n=NULL;assert(mosaic_normalization_load_file(argv[1],&n)==MOSAIC_OK);uint16_t a,b,c;assert(mosaic_normalization_unicode_version(n,&a,&b,&c)==MOSAIC_OK&&a==16&&b==0&&c==0);UErrorCode e=U_ZERO_ERROR;const UNormalizer2*norms[5]={unorm2_getNFDInstance(&e),unorm2_getNFCInstance(&e),unorm2_getNFKDInstance(&e),unorm2_getNFKCInstance(&e),unorm2_getNFKCCasefoldInstance(&e)};assert(U_SUCCESS(e));
    for(int tc=0;tc<2000;tc++){uint8_t in[256];size_t len=0;int count=1+(int)(rnd()%24);for(int j=0;j<count;j++){uint32_t cp=rnd()%0x110000u;if(cp>=0xd800&&cp<=0xdfff)cp='x';if(len+4>sizeof in)break;len+=put_utf8(in+len,cp);}for(int m=1;m<=5;m++){mosaic_normalized_view v={0};assert(mosaic_normalize(n,(mosaic_normalization_mode)m,in,len,&v)==MOSAIC_OK);uint8_t*expected=NULL;size_t en=0;assert(icu_norm(norms[m-1],in,len,&expected,&en));if(v.byte_length!=en||memcmp(v.bytes,expected,en)!=0){fprintf(stderr,"normalization mismatch case=%d mode=%d inlen=%zu\nIN=",tc,m,len);for(size_t z=0;z<len;z++)fprintf(stderr,"%02x",in[z]);fprintf(stderr,"\nGOT=");for(size_t z=0;z<v.byte_length;z++)fprintf(stderr,"%02x",v.bytes[z]);fprintf(stderr,"\nEXP=");for(size_t z=0;z<en;z++)fprintf(stderr,"%02x",expected[z]);fprintf(stderr,"\n");abort();}check_mapping(&v,len);free(expected);mosaic_normalized_view_free(&v);}}
    const uint8_t bad[]={0x41,0xff,0x65,0xcc,0x81,0xf0,0x28,0x8c,0xbc};mosaic_normalized_view v={0};assert(mosaic_normalize(n,MOSAIC_NORMALIZE_NFC,bad,sizeof bad,&v)==MOSAIC_OK);const uint8_t expected[]={0x41,0xff,0xc3,0xa9,0xf0,0x28,0x8c,0xbc};assert(v.byte_length==sizeof expected&&!memcmp(v.bytes,expected,sizeof expected));check_mapping(&v,sizeof bad);mosaic_normalized_view_free(&v);
    mosaic_tokenizer *tok=NULL;assert(mosaic_tokenizer_load_files(argv[2],argv[3],&tok)==MOSAIC_OK);uint8_t before[32],after[32];assert(mosaic_tokenizer_fingerprint(tok,before)==MOSAIC_OK);assert(mosaic_tokenizer_set_normalization_file(tok,argv[1])==MOSAIC_OK);assert(mosaic_tokenizer_normalization_loaded(tok));assert(mosaic_tokenizer_set_normalization_file(tok,argv[1])==MOSAIC_ERROR_CONFLICT);assert(mosaic_tokenizer_fingerprint(tok,after)==MOSAIC_OK);assert(memcmp(before,after,32)!=0);const uint8_t sample[]={0x65,0xcc,0x81};mosaic_normalized_view hv={0};assert(mosaic_tokenizer_normalize(tok,MOSAIC_NORMALIZE_NFC,sample,sizeof sample,&hv)==MOSAIC_OK);assert(hv.byte_length==2&&hv.bytes[0]==0xc3&&hv.bytes[1]==0xa9);mosaic_normalized_view_free(&hv);mosaic_tokenizer_free(tok);
    mosaic_normalization_free(n);puts("OK normalization Unicode16 ICU differential cases=10000 + exact mapping invariants + malformed UTF-8 barrier + tokenizer fingerprint");return 0;}
