#include "mosaic.h"
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define CHECK(x) do{if(!(x)){fprintf(stderr,"CHECK failed %s:%d: %s\n",__FILE__,__LINE__,#x);return 1;}}while(0)
static uint64_t state=UINT64_C(0x726573796e637465);static uint32_t rnd(void){state^=state<<13;state^=state>>7;state^=state<<17;return(uint32_t)state;}
static int same_model(mosaic_resync_document*d,mosaic_model*m,const uint8_t*b,size_t n){uint32_t*a=NULL,*z=NULL;size_t an=0,zn=0;if(mosaic_resync_document_encode(d,&a,&an)!=MOSAIC_OK||mosaic_encode(m,b,n,&z,&zn)!=MOSAIC_OK)return 0;int ok=an==zn&&(!an||!memcmp(a,z,an*sizeof*a));mosaic_free(a);mosaic_free(z);return ok;}
static int same_tok(mosaic_resync_document*d,mosaic_tokenizer*t,const uint8_t*b,size_t n){uint32_t*a=NULL,*z=NULL;size_t an=0,zn=0;if(mosaic_resync_document_encode(d,&a,&an)!=MOSAIC_OK||mosaic_tokenizer_encode(t,b,n,&z,&zn)!=MOSAIC_OK)return 0;int ok=an==zn&&(!an||!memcmp(a,z,an*sizeof*a));mosaic_free(a);mosaic_free(z);return ok;}
int main(int argc,char**argv){CHECK(argc==7);size_t edit_cases=500;const char*env_edits=getenv("MOSAIC_RESYNC_EDITS");if(env_edits&&*env_edits){char*end=NULL;unsigned long v=strtoul(env_edits,&end,10);CHECK(end&&!*end&&v>0&&v<=100000);edit_cases=(size_t)v;}mosaic_model*m=NULL;CHECK(mosaic_model_load_file(argv[1],&m)==MOSAIC_OK);size_t cap=1024u*1024u,len=512u*1024u;uint8_t*b=(uint8_t*)malloc(cap);CHECK(b);for(size_t i=0;i<len;++i)b[i]=(uint8_t)("hello tokenizer world \n"[i%22]);mosaic_resync_document*d=NULL;CHECK(mosaic_resync_document_create(m,b,len,16384,262144,&d)==MOSAIC_OK);CHECK(same_model(d,m,b,len));size_t resyncs=0,total_reprocessed=0,total_len=0;
for(size_t tc=0;tc<edit_cases;++tc){size_t start=rnd()%(len+1u),maxdel=len-start;if(maxdel>32)maxdel=32;size_t del=maxdel?rnd()%(maxdel+1u):0;uint8_t repl[32];size_t rn=rnd()%33u;for(size_t i=0;i<rn;++i)repl[i]=(uint8_t)rnd();CHECK(len-del+rn<=cap);memmove(b+start+rn,b+start+del,len-start-del);if(rn)memcpy(b+start,repl,rn);len=len-del+rn;mosaic_status st=mosaic_resync_document_apply_edit(d,start,del,repl,rn);CHECK(st==MOSAIC_OK);CHECK(same_model(d,m,b,len));if(mosaic_resync_document_last_resynchronized(d))++resyncs;CHECK(mosaic_resync_document_last_reprocessed_bytes(d)<=len);total_reprocessed+=mosaic_resync_document_last_reprocessed_bytes(d);total_len+=len;}
uint8_t*copy=NULL;size_t cn=0;CHECK(mosaic_resync_document_copy_bytes(d,&copy,&cn)==MOSAIC_OK);CHECK(cn==len&&!memcmp(copy,b,len));mosaic_free(copy);mosaic_resync_document_free(d);
/* Deterministic middle edit should stop at the next stable checkpoint and reuse both sides. */
len=512u*1024u;for(size_t i=0;i<len;++i)b[i]=(uint8_t)("hello tokenizer world \n"[i%22]);CHECK(mosaic_resync_document_create(m,b,len,16384,262144,&d)==MOSAIC_OK);size_t mid=len/2;const uint8_t q[]="XYZ";memcpy(b+mid,q,3);CHECK(mosaic_resync_document_apply_edit(d,mid,3,q,3)==MOSAIC_OK);CHECK(same_model(d,m,b,len));CHECK(mosaic_resync_document_last_resynchronized(d));size_t rp=mosaic_resync_document_last_reprocessed_bytes(d),pre=mosaic_resync_document_last_reused_prefix_bytes(d),suf=mosaic_resync_document_last_reused_suffix_bytes(d);CHECK(rp<65536);CHECK(pre>mid-65536);CHECK(suf>len/3);mosaic_resync_document_free(d);
/* Explicit language-specialized checkpoint state uses the same exact proof. */
mosaic_tokenizer*t=NULL;CHECK(mosaic_tokenizer_load_files(argv[1],argv[2],&t)==MOSAIC_OK);CHECK(mosaic_tokenizer_add_language_file(t,argv[3])==MOSAIC_OK);CHECK(mosaic_tokenizer_add_language_file(t,argv[4])==MOSAIC_OK);CHECK(mosaic_tokenizer_add_language_file(t,argv[5])==MOSAIC_OK);const uint8_t mixed[]="tokenizer \xe0\xa4\xa8\xe0\xa4\xae\xe0\xa4\xb8\xe0\xa5\x8d\xe0\xa4\xa4\xe0\xa5\x87 \xe3\x81\x93\xe3\x82\x93\xe3\x81\xab\xe3\x81\xa1\xe3\x81\xaf\xe4\xb8\x96\xe7\x95\x8c";CHECK(mosaic_tokenizer_resync_document_create(t,mixed,sizeof mixed-1,16,4096,&d)==MOSAIC_OK);CHECK(same_tok(d,t,mixed,sizeof mixed-1));mosaic_resync_document_free(d);mosaic_tokenizer_free(t);
mosaic_model*bpe=NULL;CHECK(mosaic_model_load_file(argv[6],&bpe)==MOSAIC_OK);CHECK(mosaic_resync_document_create(bpe,(const uint8_t*)"abc",3,16,4096,&d)==MOSAIC_ERROR_UNSUPPORTED);CHECK(!d);mosaic_model_free(bpe);mosaic_model_free(m);free(b);printf("OK checkpoint resync: edits=%zu resynchronized=%zu avg_reprocessed=%.2f%% middle=%zu prefix=%zu suffix=%zu\n",edit_cases,resyncs,total_len?100.0*(double)total_reprocessed/(double)total_len:0.0,rp,pre,suf);return 0;}
